var date = new Date()

console.log(date)
console.log(date.toDateString())
console.log(date.toTimeString())
console.log(date.toJSON())
console.log(date.toLocaleString())
console.log(date.getDate())
console.log(date.getDay())
console.log(date.getFullYear())
console.log(date.getHours())
console.log(date.getMinutes())
console.log(date.getMonth())
